SolidSteel/urls.py
# SolidSteel/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu.urls')),
    path('login/', include('login.urls')),# Incluye las URLs de la aplicación "menu"
    path('register/', include('register.urls')),# Incluye las URLs de la aplicación "menu"
    path('cart/', include('cart.urls')),# Incluye las URLs de la aplicación "cart"
    path('shipping/', include('shipping.urls')),# Incluye las URLs de la aplicación "Envios"
    path('products/', include('product.urls')), # Incluye las URLs de la aplicación "product"
    path('recycler/', include('recycler.urls')),
    path('supplier/', include('supplier.urls')),
    path('client/', include('client.urls')),
    path('accounts/', include('allauth.urls')), #new url para google
    path('pagos/', include('pay.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pay/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("", views.mostrar_pagos_view, name="mostrar_pagos"),  # Página de pago
    path("iniciar/", views.iniciar_pago_view, name="iniciar_pago"),
    path("exitoso/", views.pago_exitoso_view, name="pago_exitoso"),
    path("cancelado/", views.pago_cancelado_view, name="pago_cancelado"),# Ruta para la página principal
    path("escojer_metodo/", views.escojer_metodo_view, name="escojer_metodo"),# Ruta para la página principal
    path('create-payout/', views.create_payout, name='create_payout'),
    path("historial-compras/", views.historial_compras_view, name="historial_compras"),
]

supplier/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.supplier_menu, name='supplier_menu'),
    path('edit_info/', views.supplier_edit_info, name='supplier_edit_info'),
    path('actualizar-inventario/', views.update_stock, name='update_stock'),
    path('agregar-producto/', views.add_product, name='add_product'),
    path('saldo/', views.saldo_view, name='saldo_view'),  # Vista para mostrar el saldo
    path('saldo/retirar/', views.retirar_saldo, name='saldo_retirar'),  # Vista para retirar saldo
    path('saldo/actualizar/', views.actualizar_datos_retiro, name='saldo_actualizar_datos'),  # Vista para actualizar datos de retiro
    path('todos_movimientos/', views.todos_los_movimientos, name='todos_los_movimientos'),
    path('retiro_saldo/', views.retirar_saldo_view, name='retirar_saldo'),
    path('editar-retiro/', views.add_supplier_payment_method, name='editar_retiro'),
    path('confirmacion-retiro/', views.confirmacion_retiro, name='confirmacion_retiro'),
    path('configurar-datos/', views.configurar_datos, name='configurar_datos'),
    path('cerrar-sesion/', views.log_out, name='log_out'),
    path('delete-product/', views.delete_product, name='delete_product')
]

supplier/models.py
from django.db import models


class DatosRetiro(models.Model):
    nombre_titular = models.CharField(max_length=100)
    cuenta_paypal = models.EmailField()

    def __str__(self):
        return f"{self.nombre_titular} - {self.cuenta_paypal}"

supplier/forms.py
from django import forms
from product.models import Supplier, Product, SupplierPaymentMethodModel


class SupplierForm(forms.ModelForm):
    """
    Formulario para gestionar información básica de un proveedor.

    Campos:
        - user_email: Email del usuario asociado al proveedor.
        - user_password: Contraseña del usuario (opcional).
        - supplier_name: Nombre de la empresa proveedora.
        - supplier_address: Dirección de la empresa.
        - supplier_state: Estado donde se encuentra la empresa.
        - supplier_city: Ciudad donde se encuentra la empresa.
        - supplier_zip_code: Código postal de la empresa.

    Notas:
        - Este formulario incluye campos adicionales no presentes en el modelo `Supplier` (email y password).
    """
    user_email = forms.EmailField()
    user_password = forms.CharField(
        widget=forms.PasswordInput(),
        required=False  # No requerido, solo si desean cambiar la contraseña
    )

    class Meta:
        model = Supplier
        fields = ['supplier_name', 'supplier_address', 'supplier_state', 'supplier_city', 'supplier_zip_code']

        
        


class SupplierPaymentMethodForm(forms.ModelForm):
    """
    Formulario para gestionar métodos de pago del proveedor.
    Participantes:
    Almanza Quezada Andres Yahir 215993
    Campos:
        - supplier_payment_method: Método de pago (ej. PayPal).
        - supplier_payment_email: Correo asociado al método de pago.
        - supplier_payment_name: Nombre asociado al método de pago.

    Notas:
        - Las etiquetas (`labels`) personalizan cómo se muestran los nombres de los campos en la interfaz.
    """
    class Meta:
        model = SupplierPaymentMethodModel
        fields = ['supplier_payment_method', 'supplier_payment_email', 'supplier_payment_name']
        labels = {
            'supplier_payment_method': 'Payment Method',
            'supplier_payment_email': 'PayPal Email',
            'supplier_payment_name': 'PayPal Account Name'
        }

from django.contrib.auth.models import User
class ActualizarDatosForm(forms.ModelForm):
    """
    Formulario para actualizar los datos básicos de un usuario.
    Participantes:
    Almanza Quezada Andres Yahir 215993
    Campos:
        - first_name: Nombre del usuario.
        - last_name: Apellido del usuario.
        - email: Correo electrónico del usuario.

    Notas:
        - Basado en el modelo `User` proporcionado por Django.
    """
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class AgregarProductoForm(forms.ModelForm):
    """
    Formulario para agregar o editar un producto.
    Participantes:
    Almanza Quezada Andres Yahir 215993
    Campos:
        - product_name: Nombre del producto.
        - product_description: Descripción del producto.
        - product_price: Precio del producto.
        - product_stock: Cantidad disponible en inventario.
        - product_image: Imagen del producto.
        - product_width: Ancho del producto.
        - product_height: Alto del producto.
        - product_thickness: Grosor del producto.
        - product_material: Material del producto (opciones predefinidas).

    Validaciones personalizadas:
        - product_name: Máximo 50 caracteres.
        - product_description: Máximo 100 caracteres.
        - product_price: Entre 0.01 y 9999.
        - product_stock: Entre 1 y 9999.
        - product_width, product_height, product_thickness: Entre 0.01 y 9999.
        - product_image: Solo formatos JPG y PNG.

    Notas:
        - Las opciones para el campo `product_material` están predefinidas como una lista de tuplas.
        - Los widgets se usan para estilizar los campos en el frontend.
    """
    MATERIAL_CHOICES = [
        ('Metal', 'Metal'),
        ('Acero', 'Acero'),
        ('Aluminio', 'Aluminio'),
        ('Bronce', 'Bronce'),
    ]

    product_material = forms.ChoiceField(
        choices=MATERIAL_CHOICES,
        widget=forms.Select(attrs={'class': 'form-control cantidad'})
    )

    class Meta:
        model = Product
        fields = [
            'product_name', 'product_description', 'product_price', 'product_stock',
            'product_image', 'product_width', 'product_height', 'product_thickness', 'product_material'
        ]
        widgets = {
            'product_name': forms.TextInput(attrs={'class': 'form-control cantidad'}),
            'product_description': forms.Textarea(attrs={'class': 'form-control cantidad', 'rows': 1}),
            'product_price': forms.NumberInput(attrs={'class': 'form-control cantidad'}),
            'product_stock': forms.NumberInput(attrs={'class': 'form-control cantidad'}),
            'product_image': forms.ClearableFileInput(attrs={'class': 'form-control cantidad'}),
            'product_width': forms.NumberInput(attrs={'class': 'form-control cantidad'}),
            'product_height': forms.NumberInput(attrs={'class': 'form-control cantidad'}),
            'product_thickness': forms.NumberInput(attrs={'class': 'form-control cantidad'}),
        }
        labels = {
            'product_name': 'Nombre del Producto',
            'product_description': 'Descripción del Producto',
            'product_price': 'Precio',
            'product_stock': 'Cantidad en Inventario',
            'product_image': 'Imagen del Producto',
            'product_width': 'Ancho del Producto',
            'product_height': 'Alto del Producto',
            'product_thickness': 'Grosor del Producto',
            'product_material': 'Material del Producto',
        }

    def clean_product_name(self):
        name = self.cleaned_data.get('product_name')
        if len(name) > 50:
            raise forms.ValidationError("El nombre del producto no puede tener más de 50 caracteres.")
        return name

    def clean_product_description(self):
        description = self.cleaned_data.get('product_description')
        if len(description) > 100:
            raise forms.ValidationError("La descripción debe ser menor a 100 caracteres.")
        return description

    def clean_product_price(self):
        price = self.cleaned_data.get('product_price')
        if price <= 0 or price > 9999:
            raise forms.ValidationError("El precio debe ser mayor a 0 y no exceder 9999.")
        return price

    def clean_product_stock(self):
        stock = self.cleaned_data.get('product_stock')
        if stock <= 0 or stock > 9999:
            raise forms.ValidationError("La cantidad en inventario debe ser mayor a 0 y no exceder 9999.")
        return stock

    def clean_product_width(self):
        width = self.cleaned_data.get('product_width')
        if width < 0.01 or width > 9999:
            raise forms.ValidationError("El ancho debe ser al menos 0.01 y no exceder 9999.")
        return width

    def clean_product_height(self):
        height = self.cleaned_data.get('product_height')
        if height < 0.01 or height > 9999:
            raise forms.ValidationError("El alto debe ser al menos 0.01 y no exceder 9999.")
        return height

    def clean_product_thickness(self):
        thickness = self.cleaned_data.get('product_thickness')
        if thickness < 0.01 or thickness > 9999:
            raise forms.ValidationError("El grosor debe ser al menos 0.01 y no exceder 9999.")
        return thickness

    def clean_product_image(self):
        image = self.cleaned_data.get('product_image')
        if image:
            if not image.name.lower().endswith(('.jpg', '.jpeg', '.png')):
                raise forms.ValidationError("Solo se permiten archivos de imagen JPG y PNG.")
        return image

class ActualizarProductosForm(forms.ModelForm):
    """
    Formulario para actualizar el precio y la cantidad en inventario de un producto.
    Participantes:
    Almanza Quezada Andres Yahir 215993
    Modelo relacionado:
        - Product

    Campos:
        - product_price: Precio del producto.
        - product_stock: Cantidad en inventario del producto.

    Uso:
        - Permite a los usuarios modificar solo el precio y el inventario de un producto existente.
    """
    class Meta:
        model = Product
        fields = ['product_price', 'product_stock']


class WithdrawForm(forms.Form):
    """
    Formulario para realizar retiros de saldo.
    Participantes:
    Almanza Quezada Andres Yahir 215993
    Campos:
        - cantidad: Cantidad a retirar (mínimo 0.01).

    Características:
        - Campo `cantidad` validado para aceptar solo valores mayores o iguales a 0.01.
        - Usa un widget personalizado para estilizar el campo como un campo numérico en el frontend.
        - Incluye un atributo `step` para garantizar precisión en cantidades decimales.

    Uso:
        - Este formulario es utilizado para permitir a los usuarios especificar el monto a retirar.
    """
    cantidad = forms.FloatField(
        min_value=0.01,
        widget=forms.NumberInput(attrs={
            'class': 'form-control',
            'required': True,
            'step': '0.01'
        }),
        label="Cantidad a Retirar"
    )

supplier/templates/supplier/add_product.html
{% extends "base_supplier.html" %}

{% block title %}Agregar Nuevo Producto{% endblock %}

{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/menus_supplier.css' %}">

{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2">
            <div class="d-flex justify-content-left">
                <button class="btn btn-outline-secondary" style="margin-top:20px;" onclick="window.location.href='{% url 'supplier_menu' %}'">
                    <span class="me-1">&larr;</span> Volver
                </button>
            </div>
        </div>
    </div>

    <div class="section-title text-center">
        <h2>Agregar Nuevo Producto</h2>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group">
                    <label for="id_product_name">Nombre del Producto:</label>
                    {{ form.product_name }}
                    {% for error in form.product_name.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_description">Descripción del Producto:</label>
                    {{ form.product_description }}
                    {% for error in form.product_description.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_price">Precio:</label>
                    {{ form.product_price }}
                    {% for error in form.product_price.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_stock">Cantidad en Inventario:</label>
                    {{ form.product_stock }}
                    {% for error in form.product_stock.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_image">Imagen del Producto:</label>
                    {{ form.product_image }}
                    {% for error in form.product_image.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_width">Ancho del Producto:</label>
                    {{ form.product_width }}
                    {% for error in form.product_width.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_height">Alto del Producto:</label>
                    {{ form.product_height }}
                    {% for error in form.product_height.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_thickness">Grosor del Producto:</label>
                    {{ form.product_thickness }}
                    {% for error in form.product_thickness.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="form-group">
                    <label for="id_product_material">Material del Producto:</label>
                    {{ form.product_material }}
                    {% for error in form.product_material.errors %}
                        <div class="error-message">{{ error }}</div>
                    {% endfor %}
                </div>

                <div class="text-center">
                    <button type="submit" class="btn btn-success mt-3 botones">Subir Producto</button>
                </div>
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}

supplier/templates/supplier/configurar_datos.html
{% extends "supplier/saldo.html" %}
{% load static %}

{% block title %}Configurar Datos{% endblock %}


{% block content %}

<link rel="stylesheet" href="{% static 'css/configurar_datos.css' %}">
<main class="main-container">
    <div class="container">
        <div class="section-title text-center">
            <h1>Actualizar Datos</h1>
        </div>
        <form method="POST" action="/configurar-datos/">
            <div class="row">
                <div class="col-md-6 mb-3">
                    <label for="first_name">First Name</label>
                    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="Value">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="email">Email</label>
                    <input type="email" class="form-control" id="email" name="email" placeholder="Value">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="last_name">Last Name</label>
                    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Value">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Value">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="last_second_name">Last Second Name</label>
                    <input type="text" class="form-control" id="last_second_name" name="last_second_name" placeholder="Value">
                </div>
                <div class="col-md-6 mb-3">
                    <label for="phone_number">Phone Number</label>
                    <input type="text" class="form-control" id="phone_number" name="phone_number" placeholder="Value">
                </div>
            </div>
            <div class="text-center">
                <button type="submit" class="btn btn-dark w-50 mt-4">Actualizar Datos</button>
            </div>
        </form>
    </div>
</main>
{% endblock %}

supplier/templates/supplier/confirmacion_retiro.html
{% extends "base_without_image.html" %}

{% load static %}

{% block title %}Confirmación de Retiro{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/confirmacion_retiro.css' %}">

<main class="main-container">
    <div class="text-center">
        <h1 class="title-success">TRANSACCIÓN EXITOSA</h1>
        <div class="check-icon" >
            <i class="fas fa-check-circle" style="font-size: 100px; color: #28a745;"></i>
        </div>        
    </div>
    <div class="container-confirmacion mt-5">
        <table class="table">
            <tbody>
                <tr>
                    <th>Estado de transacción</th>
                    <td>En Proceso</td>
                </tr>
                <tr>
                    <th>Nombre del comercio</th>
                    <td>Cobro de Saldo Metal Steel</td>
                </tr>
                <tr>
                    <th>Fecha de pago</th>
                    <td>22 de Septiembre</td>
                </tr>
                <tr>
                    <th>Hora de pago</th>
                    <td>18:30</td>
                </tr>
                <tr>
                    <th>ID de la transacción</th>
                    <td>#12345678910</td>
                </tr>
                <tr>
                    <th>CUS</th>
                    <td>1234567891</td>
                </tr>
                <tr>
                    <th>Cuenta</th>
                    <td>asdaeredsass@####.com</td>
                </tr>
                <tr>
                    <th>Método de pago</th>
                    <td>Paypal Transacción</td>
                </tr>
                <tr>
                    <th>Costo subtotal</th>
                    <td>$150</td>
                </tr>
                <tr>
                    <th>Total</th>
                    <td><strong>$150</strong></td>
                </tr>
            </tbody>
        </table>
        <div class="text-center mt-4">
            <button type="button" class="btn btn-primary w-100 finalizar-btn">Finalizar</button>
        </div>
    </div>
</main>
{% endblock %}

supplier/templates/supplier/editar_retiro.html
{% extends "base_supplier.html" %}

{% block title %}Editar Retiro de Saldo - Solid Steel{% endblock %}

{% block header %}
<head>
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'general/css/style_general_supplier.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">
</head>
<style>
    /* Clase personalizada para el margen superior */
.mg-top-15px {
    margin-top: 15px;
}

/* Color del botón y efecto de hover */
.btn-primary {
    background-color: #363738;
    border-color: #363738;
    transition: background-color 0.3s;
}

/* Efecto cuando el botón está activo */
.btn-primary.active {
    background-color: #404041;
    border-color: #363738;
    color: white;
}

/* Efecto cuando se pasa el cursor por encima */
.btn-primary:hover {
    background-color: #e3e6e9;
    border-color: #e5e6e7;
    color: rgb(54, 52, 52);
}
</style>
{% endblock %}

{% block content %}

<div class="container mt-5">
    <div class="d-flex justify-content-left">
        <button class="btn btn-outline-secondary" onclick="window.location.href='{% url 'saldo_view' %}'">
            <span class="me-1">&larr;</span> Volver
        </button>
    </div>
    
<main class="container mt-5">
    <div class="card-header text-center text-black">
        <h2>Editar Retiro de Saldo</h2>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card shadow">
                <div class="card-body">
                    <form id="paymentForm" method="post" novalidate>
                        {% csrf_token %}
                        <div class="mb-3 mg-top-15px">
                            <label for="id_supplier_payment_method">{{ form.supplier_payment_method.label }}</label>
                            <select id="id_supplier_payment_method" name="supplier_payment_method" class="form-control" required>
                                <option value="" selected disabled>Seleccione un método de pago</option>
                                {% for choice in form.supplier_payment_method.field.choices %}
                                    <option value="{{ choice.0 }}" {% if choice.0 == form.supplier_payment_method.value %}selected{% endif %}>{{ choice.1 }}</option>
                                {% endfor %}
                            </select>
                            <div class="invalid-feedback">Por favor, seleccione un método de pago.</div>
                        </div>
                        <div class="mb-3 mg-top-15px">
                            <label for="id_supplier_payment_email">{{ form.supplier_payment_email.label }}</label>
                            <input type="email" id="id_supplier_payment_email" name="supplier_payment_email" value="{{ form.supplier_payment_email.value }}" class="form-control" required pattern="^[^\']+$">
                            <div class="invalid-feedback">Por favor, ingrese un email válido sin comillas simples.</div>
                        </div>
                        <div class="mb-3 mg-top-15px">
                            <label for="id_supplier_payment_name">{{ form.supplier_payment_name.label }}</label>
                            <input type="text" id="id_supplier_payment_name" name="supplier_payment_name" value="{{ form.supplier_payment_name.value }}" class="form-control" required pattern="^[a-zA-Z0-9\s]{1,50}$">
                            <div class="invalid-feedback">El nombre debe contener solo letras, números y espacios, y no debe exceder los 50 caracteres.</div>
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Guardar Método de Pago</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</main>
<footer class="bg-light text-center py-4 mt-5">
    <div class="container">
        <p class="mt-3">&copy; 2024 Solid Steel. Todos los derechos reservados.</p>
    </div>
</footer>

<script>
    // Validación del formulario
    document.getElementById('paymentForm').addEventListener('submit', function(event) {
        // Obtenemos todos los campos del formulario
        var form = this;
        var isValid = true;

        // Validar método de pago
        var paymentMethod = form.supplier_payment_method;
        if (!paymentMethod.value) {
            paymentMethod.classList.add('is-invalid');
            isValid = false;
        } else {
            paymentMethod.classList.remove('is-invalid');
        }

        // Validar email
        var email = form.supplier_payment_email;
        var emailPattern = /^[^\']+$/;
        if (!email.value || !emailPattern.test(email.value)) {
            email.classList.add('is-invalid');
            isValid = false;
        } else {
            email.classList.remove('is-invalid');
        }

        // Validar nombre de cuenta PayPal
        var accountName = form.supplier_payment_name;
        var accountNamePattern = /^[a-zA-Z0-9\s]{1,50}$/;
        if (!accountName.value || !accountNamePattern.test(accountName.value)) {
            accountName.classList.add('is-invalid');
            isValid = false;
        } else {
            accountName.classList.remove('is-invalid');
        }

        // Si hay errores, evitamos que se envíe el formulario
        if (!isValid) {
            event.preventDefault();
        }
    });
</script>
{% endblock %}

supplier/templates/supplier/retirar_saldo.html
{% extends "base_supplier.html" %}
{% block title %}Retirar saldo{% endblock title %}

{% block header %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/saldo.css' %}">
{% endblock %}

{% block content %}

<style>
    /* Clase personalizada para el margen superior */
    .mg-top-15px {
        margin-top: 15px;
    }
    
    /* Estilo del campo de entrada */
    input.form-control {
        border: 1px solid #ddd;
        border-radius: 5px;
        padding: 10px;
        font-size: 16px;
        transition: border-color 0.3s;
    }
    
    input.form-control:focus {
        border-color: #363738;
        outline: none;
    }
    
    /* Ocultar las flechas de incremento/decremento en el campo de número */
    input[type="number"]::-webkit-outer-spin-button,
    input[type="number"]::-webkit-inner-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    input[type="number"] {
        -moz-appearance: textfield; /* Para Firefox */
    }
    
    /* Estilo del botón */
    .btn-primary {
        background-color: #363738;
        border-color: #363738;
        color: white;
        transition: background-color 0.3s, color 0.3s, border-color 0.3s;
    }
    
    .btn-primary:hover {
        background-color: #2e2f30;
        border-color: #2e2f30;
        color: white;
    }
</style>


<div class="container mt-5">
    <div class="d-flex justify-content-left">
        <button class="btn btn-outline-secondary" onclick="window.location.href='{% url 'saldo_view' %}'">
            <span class="me-1">&larr;</span> Volver
        </button>
    </div>
    {% if messages %}
        <div class="mt-3">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        </div>
    {% endif %}
<main class="container mt-5">
    <div class="section-title text-center">
        <h1>Retiro de saldo</h1>
    </div>
    <div class="row justify-content-center">
        <!-- Sección del saldo y cuenta -->
        <div class="col-md-5 saldo">
            <h2 class="text-center">Saldo</h2>
            <div class="saldo-info text-center">
                <i class="fas fa-wallet saldo-icon"></i> <!-- Icono de la cartera -->
                <span class="saldo-cantidad d-block" id="saldo">{{ supplier.balance }}</span>
            </div>

            <!-- Botones y campo de cantidad -->
            <div class="mt-4">
                <form id="withdrawForm" method="POST" action="{% url 'create_payout' %}">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="cantidad" class="form-label">Cantidad a Retirar:</label>
                        <input type="number" id="cantidad" name="cantidad" min="0.01" step="0.01" class="form-control" required>
                    </div>
                    <button type="submit" class="btn btn-primary w-100">Retirar Dinero</button>
                    <!-- Contenedor para el mensaje de error -->
                    <div class="text-danger mt-2" id="error-message" style="display: none;"></div>
                </form>
            </div>
        </div>

        <!-- Sección de detalles -->
        <div class="col-md-4 detalles-titular">
            <h5 class="fw-bold">Nombre del titular</h5>
            <p>{{ pago.supplier_payment_name }}</p>
            <h5 class="fw-bold">Cuenta de Paypal</h5>
            <p>{{ pago.supplier_payment_email }}</p>
        </div>
    </div>
</main>

<script>
    document.getElementById('withdrawForm').addEventListener('submit', function(event) {
        // Obtener el saldo y la cantidad a retirar
        var saldoDisponible = parseFloat(document.getElementById('saldo').textContent);
        var cantidadRetirar = parseFloat(document.getElementById('cantidad').value);

        // Validar si la cantidad a retirar es válida y si hay suficiente saldo
        if (isNaN(cantidadRetirar) || cantidadRetirar <= 0 || cantidadRetirar > saldoDisponible) {
            event.preventDefault(); // Evitar que se envíe el formulario
            var errorMessage = "No tienes suficiente saldo para retirar esta cantidad.";
            if (isNaN(cantidadRetirar) || cantidadRetirar <= 0) {
                errorMessage = "Por favor, ingrese una cantidad válida para retirar.";
            }
            document.getElementById('error-message').textContent = errorMessage;
            document.getElementById('error-message').style.display = "block";
        } else {
            document.getElementById('error-message').style.display = "none";
        }
    });
</script>

{% endblock %}